export interface GrindingInt {
    Customer: string,
    PartNo: string,
    PartName: string,
    MAGrindingMachine: string,
    SSEPLoadingPlateNo: string,
    GrindingSpeed: string,
    GrindingAngle: string,
    LoG: string,
    e1: string,
    e2: string,
    ODg: string,
    MALSTube1: string,
    MALSTube1Quant: string,
    MALSTube2: string,
    MALSTube2Quant: string,
    MALSTube3: string,
    MALSTube3Quant: string,
    SSEPODDisk: string,
    SSEPThicknessDisk: string,
    SSEPIdBush: string,
    SSEPThicknessBush: string,
    SSEPODBush: string,
    SSEPHoleF: string,
    SSEPLoBush: string,
    upto: Date
}
